# Generated by Django 5.2.5 on 2026-08-23 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('cooperative', 'Cooperative'), ('company', 'Company')], default='individual', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='can_buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('organization', 'Organization'), ('admin', 'Admin')], default='buyer', max_length=16),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=180)),
                ('registration_number', models.CharField(max_length=80, unique=True)),
                ('tax_number', models.CharField(blank=True, max_length=80)),
                ('representative_name', models.CharField(max_length=140)),
                ('representative_role', models.CharField(max_length=100)),
                ('business_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=12)),
                ('member_count', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
