# Generated by Django 5.2.5 on 2026-08-23 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_account_type_user_can_buy_user_can_sell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
