from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("core", "0007_platformsetting_orderreview_smartcontract_and_more")]
    operations = [
        migrations.AddField(model_name="dispute", name="evidence", field=models.JSONField(default=list)),
        migrations.AddField(model_name="dispute", name="decision", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="dispute", name="resolution_note", field=models.TextField(blank=True)),
        migrations.AddField(model_name="dispute", name="refund_amount", field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
        migrations.AddField(model_name="dispute", name="decided_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="dispute", name="decided_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="decided_disputes", to=settings.AUTH_USER_MODEL)),
        migrations.CreateModel(name="AuditLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("action", models.CharField(max_length=100)), ("target_type", models.CharField(max_length=80)), ("target_id", models.CharField(max_length=80)), ("metadata", models.JSONField(default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="audit_actions", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="TransporterProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("vehicle_type", models.CharField(max_length=120)), ("capacity_kg", models.PositiveIntegerField()), ("license_reference", models.CharField(max_length=120)), ("verification_status", models.CharField(choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected"), ("suspended", "Suspended")], default="pending", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="transporter_profile", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Delivery", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("pickup_location", models.CharField(max_length=180)), ("delivery_location", models.CharField(max_length=180)), ("status", models.CharField(choices=[("unassigned", "Unassigned"), ("assigned", "Assigned"), ("picked_up", "Picked up"), ("delivered", "Delivered"), ("cancelled", "Cancelled")], default="unassigned", max_length=20)), ("assigned_at", models.DateTimeField(blank=True, null=True)), ("picked_up_at", models.DateTimeField(blank=True, null=True)), ("delivered_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="delivery", to="core.order")), ("transporter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="deliveries", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="PaymentReconciliation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("provider", models.CharField(max_length=40)), ("provider_reference", models.CharField(max_length=120, unique=True)), ("expected_amount", models.DecimalField(decimal_places=2, max_digits=14)), ("settled_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)), ("status", models.CharField(choices=[("pending", "Pending"), ("matched", "Matched"), ("mismatch", "Mismatch"), ("refunded", "Refunded")], default="pending", max_length=20)), ("provider_payload", models.JSONField(default=dict)), ("reconciled_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reconciliations", to="core.order")), ("reconciled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reconciled_payments", to=settings.AUTH_USER_MODEL))]),
    ]
