from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("core", "0008_operations_and_audit")]
    operations = [
        migrations.AlterField(model_name="order", name="status", field=models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("accepted", "Accepted"), ("packed", "Packed"), ("dispatched", "Dispatched"), ("delivered", "Delivered"), ("completed", "Completed"), ("partially_fulfilled", "Partially Fulfilled"), ("failed_delivery", "Failed Delivery"), ("disputed", "Disputed"), ("cancelled", "Cancelled"), ("refunded", "Refunded"), ("fulfilled", "Fulfilled")], default="pending", max_length=20)),
        migrations.AddField(model_name="order", name="acceptance_deadline", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="order", name="cancellation_reason", field=models.TextField(blank=True)),
        migrations.AddField(model_name="orderitem", name="fulfilled_quantity", field=models.PositiveIntegerField(default=0)),
        migrations.CreateModel(name="OrderStatusHistory", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("from_status", models.CharField(blank=True, max_length=30)), ("to_status", models.CharField(max_length=30)), ("reason", models.TextField(blank=True)), ("metadata", models.JSONField(default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="core.order"))]),
        migrations.CreateModel(name="DeliveryEvidence", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("evidence_type", models.CharField(choices=[("pickup", "Pickup"), ("dispatch", "Dispatch"), ("delivery", "Delivery"), ("failed_delivery", "Failed delivery")], max_length=24)), ("file", models.FileField(blank=True, upload_to="delivery-evidence/")), ("reference", models.CharField(blank=True, max_length=240)), ("note", models.TextField(blank=True)), ("location", models.CharField(blank=True, max_length=180)), ("created_at", models.DateTimeField(auto_now_add=True)), ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="delivery_evidence", to="core.order"))]),
        migrations.CreateModel(name="Refund", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("amount", models.DecimalField(decimal_places=2, max_digits=14)), ("provider", models.CharField(max_length=40)), ("provider_reference", models.CharField(max_length=120, unique=True)), ("status", models.CharField(choices=[("requested", "Requested"), ("submitted", "Submitted"), ("settled", "Settled"), ("failed", "Failed")], default="requested", max_length=20)), ("reason", models.TextField()), ("provider_payload", models.JSONField(default=dict)), ("settled_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="refunds", to="core.order")), ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_refunds", to=settings.AUTH_USER_MODEL))]),
    ]
