# Generated by Django 5.2.5 on 2026-08-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delivery_delivery_fee_delivery_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_orders', to='core.organization'),
        ),
    ]
