# Generated by Django 5.2.5 on 2026-08-29 08:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='allow_partial_fulfilment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='certification',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_radius_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='minimum_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='moisture_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pack_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='storage_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('tonne', 'Tonne'), ('bag', 'Bag'), ('crate', 'Crate'), ('litre', 'Litre'), ('item', 'Item')], default='item', max_length=16),
        ),
        migrations.AddField(
            model_name='listing',
            name='variety',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WantedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('tonne', 'Tonne'), ('bag', 'Bag'), ('crate', 'Crate'), ('litre', 'Litre'), ('item', 'Item')], default='item', max_length=16)),
                ('maximum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='core.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_favourite_listing')],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='core.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_recent_listing')],
            },
        ),
        migrations.CreateModel(
            name='WholesalePriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_tiers', to='core.listing')),
            ],
            options={
                'ordering': ['minimum_quantity'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'minimum_quantity'), name='unique_listing_wholesale_tier')],
            },
        ),
    ]
