# Generated by Django 5.2.5 on 2026-08-29 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listing_allow_partial_fulfilment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('http', 'Http'), ('payment_webhook', 'Payment Webhook'), ('ussd', 'Ussd'), ('uptime', 'Uptime'), ('backup', 'Backup'), ('alert', 'Alert')], max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=24)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('service', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('message', models.TextField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
