# Generated by Django 5.2.5 on 2026-08-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_protected_cloudinary_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='World Bank Microdata Library', max_length=120)),
                ('source_dataset', models.CharField(default='MWI_2021_RTFP_v02_M', max_length=80)),
                ('source_version', models.DateField()),
                ('source_url', models.URLField(default='https://microdata.worldbank.org/catalog/6171')),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=120)),
                ('geo_id', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price_date', models.DateField(db_index=True)),
                ('crop', models.CharField(choices=[('beans', 'Beans'), ('cassava', 'Cassava'), ('groundnuts', 'Groundnuts'), ('maize', 'Maize'), ('rice', 'Rice')], db_index=True, max_length=20)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('unit', models.CharField(default='kg', max_length=16)),
                ('opening_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('closing_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('trust_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recent_data_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('index_confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('spatially_interpolated', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-price_date', 'market', 'crop'],
                'indexes': [models.Index(fields=['crop', 'price_date'], name='market_crop_date_idx'), models.Index(fields=['district', 'market'], name='market_location_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_version', 'geo_id', 'price_date', 'crop'), name='unique_historical_market_price')],
            },
        ),
    ]
