# Generated by Django 5.2.5 on 2026-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_historicalmarketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarketprice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmarketprice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
