# Generated by Django 5.2.5 on 2026-08-30 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_historicalmarketprice_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='kindwise_crop_health', max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('crop', models.CharField(blank=True, max_length=80)),
                ('image_sha256', models.CharField(max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=180)),
                ('consent_version', models.CharField(max_length=20)),
                ('consented_at', models.DateTimeField()),
                ('results', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('provider_error', 'Provider_Error'), ('deletion_pending', 'Deletion_Pending'), ('deleted', 'Deleted')], default='completed', max_length=24)),
                ('remote_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.cropdiagnosis')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_escalations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('harmful_advice', 'Harmful Advice'), ('incorrect_result', 'Incorrect Result'), ('unsafe_pesticide', 'Unsafe Pesticide'), ('privacy', 'Privacy'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.cropdiagnosis')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
