# Generated by Django 5.2.5 on 2026-08-30 18:04

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_geocodingcache_geocodingrequeststate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerdFlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('pigs', 'Pigs'), ('chickens_broilers', 'Chickens Broilers'), ('chickens_layers', 'Chickens Layers'), ('chickens_indigenous', 'Chickens Indigenous'), ('ducks', 'Ducks'), ('rabbits', 'Rabbits'), ('other', 'Other')], max_length=32)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('head_count', models.PositiveIntegerField(default=0)),
                ('housing', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('closed', 'Closed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='herds_flocks', to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herds_flocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('estimated_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('missing', 'Missing')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='core.herdflock')),
            ],
        ),
        migrations.CreateModel(
            name='LiveAnimalListingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('pigs', 'Pigs'), ('chickens_broilers', 'Chickens Broilers'), ('chickens_layers', 'Chickens Layers'), ('chickens_indigenous', 'Chickens Indigenous'), ('ducks', 'Ducks'), ('rabbits', 'Rabbits'), ('other', 'Other')], max_length=32)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('mixed', 'Mixed')], default='mixed', max_length=12)),
                ('age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('live_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vaccination_summary', models.TextField(blank=True)),
                ('welfare_declaration', models.BooleanField(default=False)),
                ('movement_permit_reference', models.CharField(blank=True, max_length=120)),
                ('veterinary_certificate', models.FileField(blank=True, storage=core.storage.AdaptiveCloudinaryStorage(protected=True), upload_to='live-animal-documents/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_listings', to='core.herdflock')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_animal_detail', to='core.listing')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_live_animal_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockDeliveryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_permit_reference', models.CharField(blank=True, max_length=120)),
                ('vehicle_suitable', models.BooleanField(default=False)),
                ('ventilation_confirmed', models.BooleanField(default=False)),
                ('cleaning_confirmed', models.BooleanField(default=False)),
                ('stocking_plan', models.TextField(blank=True)),
                ('welfare_plan', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_requirements', to='core.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockHealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('illness', 'Illness'), ('injury', 'Injury'), ('inspection', 'Inspection'), ('quarantine', 'Quarantine'), ('birth', 'Birth'), ('death', 'Death')], max_length=24)),
                ('occurred_on', models.DateField()),
                ('description', models.TextField()),
                ('product_or_vaccine', models.CharField(blank=True, max_length=140)),
                ('administered_by', models.CharField(blank=True, max_length=140)),
                ('withdrawal_end_date', models.DateField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, storage=core.storage.AdaptiveCloudinaryStorage(protected=True), upload_to='livestock-health/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events', to='core.animalrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_livestock_health_events', to=settings.AUTH_USER_MODEL)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='core.herdflock')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('eggs', 'Eggs'), ('milk', 'Milk'), ('manure', 'Manure'), ('live_weight', 'Live Weight'), ('feed_used', 'Feed Used'), ('mortality', 'Mortality')], max_length=20)),
                ('recorded_on', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='core.herdflock')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=160)),
                ('production_system', models.CharField(choices=[('pastoral', 'Pastoral'), ('mixed', 'Mixed'), ('intensive', 'Intensive'), ('free_range', 'Free Range'), ('backyard', 'Backyard')], default='mixed', max_length=24)),
                ('species_kept', models.JSONField(default=list)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('traditional_authority', models.CharField(blank=True, max_length=100)),
                ('biosecurity_notes', models.TextField(blank=True)),
                ('veterinary_contact', models.CharField(blank=True, max_length=140)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=140)),
                ('due_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.animalrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_reminders', to='core.herdflock')),
            ],
        ),
        migrations.AddConstraint(
            model_name='animalrecord',
            constraint=models.UniqueConstraint(fields=('herd', 'identifier'), name='unique_animal_identifier_per_herd'),
        ),
    ]
