# Generated by Django 5.2.5 on 2026-08-30 18:40

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_herdflock_animalrecord_liveanimallistingdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalrecord',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animalrecord',
            name='acquisition_type',
            field=models.CharField(choices=[('birth', 'Birth'), ('purchase', 'Purchase'), ('transfer', 'Transfer'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='animalrecord',
            name='breeding_status',
            field=models.CharField(choices=[('not_recorded', 'Not recorded'), ('not_breeding', 'Not breeding'), ('breeding', 'Breeding'), ('pregnant', 'Pregnant'), ('lactating', 'Lactating')], default='not_recorded', max_length=24),
        ),
        migrations.AddField(
            model_name='herdflock',
            name='traceability_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestock_herd', to='core.traceabilitybatch'),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='animal_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='breeding_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='handling_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='health_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='production_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='purpose',
            field=models.CharField(choices=[('breeding', 'Breeding'), ('meat', 'Meat'), ('milk', 'Milk'), ('eggs', 'Eggs'), ('draught', 'Draught'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='sale_format',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='group', max_length=16),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='sale_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='liveanimallistingdetail',
            name='transport_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestockdeliveryrequirement',
            name='disinfection_record',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livestockdeliveryrequirement',
            name='maximum_stocking_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockdeliveryrequirement',
            name='transporter_authorization_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='deliveryevidence',
            name='evidence_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('loading', 'Loading'), ('dispatch', 'Dispatch'), ('unloading', 'Unloading'), ('delivery', 'Delivery'), ('failed_delivery', 'Failed delivery')], max_length=24),
        ),
        migrations.CreateModel(
            name='AnimalWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to='core.animalrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalWelfareReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('details', models.TextField()),
                ('evidence', models.FileField(blank=True, storage=core.storage.AdaptiveCloudinaryStorage(protected=True), upload_to='animal-welfare-reports/%Y/%m/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_welfare_reports', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_reports', to='core.delivery')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_reports', to='core.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_welfare_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=40)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=12)),
                ('message', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.herdflock')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockBreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('mating', 'Mating'), ('insemination', 'Insemination'), ('pregnancy_check', 'Pregnancy Check'), ('birth', 'Birth'), ('weaning', 'Weaning')], max_length=24)),
                ('occurred_on', models.DateField()),
                ('expected_due_date', models.DateField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_records', to='core.animalrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='core.herdflock')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockCatalogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('species', 'Species'), ('breed', 'Breed'), ('prohibited_sale', 'Prohibited sale rule')], max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('rules', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockFinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=12)),
                ('category', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('occurred_on', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.herdflock')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockMovementRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=32)),
                ('origin_region', models.CharField(blank=True, max_length=100)),
                ('destination_region', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('source_name', models.CharField(max_length=180)),
                ('source_reference', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
