from django.urls import path
from . import views

urlpatterns = [
    path("csrf/", views.CsrfView.as_view()),
    path("auth/register/", views.RegisterView.as_view()),
    path("auth/verify-otp/", views.ProfileView.as_view()),
    path("auth/login/", views.LoginView.as_view()),
    path("auth/logout/", views.LogoutView.as_view()),
    path("auth/profile/", views.ProfileView.as_view()),
    path("auth/forgot-password/", views.ForgotPasswordView.as_view()),
    path("auth/verify-reset-otp/", views.VerifyResetCodeView.as_view()),
    path("auth/reset-password/", views.ResetPasswordView.as_view()),
    path("organizations/me/", views.OrganizationProfileView.as_view()),
    path("ussd/authenticate", views.USSDAuthenticateView.as_view()),
    path("marketplace/public-listings/", views.PublicListingList.as_view()),
    path("marketplace/listings/", views.ListingListCreate.as_view()),
    path("marketplace/listings/<int:pk>/", views.ListingDetail.as_view()),
    path("marketplace/orders/", views.OrderList.as_view()),
    path("marketplace/seller-orders/", views.SellerOrderList.as_view()),
    path("marketplace/orders/<int:pk>/", views.OrderDetail.as_view()),
    path("marketplace/orders/<int:order_id>/status/", views.OrderStatus.as_view()),
    path("marketplace/order-reviews/", views.OrderReviewCreate.as_view()),
    path("marketplace/orders/<int:order_id>/dispute/", views.DisputeCreate.as_view()),
    path("payments/checkout-sessions/", views.CheckoutView.as_view()),
    path("referrals/validate/", views.ReferralValidate.as_view()),
    path("contact/", views.ContactCreate.as_view()),
    path("newsletter/", views.NewsletterCreate.as_view()),
    path("users/notifications", views.NotificationPreferencesView.as_view()),
    path("messages/conversations/", views.ConversationListCreate.as_view()),
    path("messages/conversations/<int:conversation_id>/messages/", views.ConversationMessages.as_view()),
    path("messages/conversations/<int:conversation_id>/read/", views.ConversationRead.as_view()),
    path("notifications/", views.NotificationList.as_view()),
    path("notifications/<int:notification_id>/read/", views.NotificationRead.as_view()),
    path("notifications/read-all/", views.NotificationReadAll.as_view()),
    path("subscriptions/me/", views.SubscriptionMe.as_view()),
    path("subscriptions/checkout-sessions/", views.SubscriptionCheckout.as_view()),
    path("subscriptions/cancel/", views.SubscriptionCancel.as_view()),
    path("advisory/ai/", views.AdvisoryAI.as_view()),
    path("advisory/expert-consultations/", views.ExpertConsultationCreate.as_view()),
    path("advisory/market-data/", views.MarketData.as_view()),
    path("advisory/smart-contracts/", views.SmartContractListCreate.as_view()),
    path("dashboard/overview/", views.DashboardOverview.as_view()),
    path("analytics/overview/", views.AnalyticsOverview.as_view()),
    path("wallet/", views.WalletView.as_view()),
    path("wallet/withdrawals/", views.WithdrawalCreate.as_view()),
    path("traceability/batches/", views.TraceabilityBatchListCreate.as_view()),
    path("traceability/batches/<int:pk>/", views.TraceabilityBatchDetail.as_view()),
    path("traceability/batches/<int:batch_id>/events/", views.TraceabilityEventCreate.as_view()),
    path("traceability/verify/<str:batch_code>/", views.TraceabilityVerify.as_view()),
    path("admin/overview/", views.AdminOverview.as_view()),
    path("admin/users/", views.AdminUsers.as_view()),
    path("admin/settings/", views.AdminSettingsView.as_view()),
    path("users/account", views.DeleteAccountView.as_view()),
]
